name: Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore 
    - name: Build win-x64
      run: dotnet publish -r win-x64 -c Release --self-contained --no-restore && zip -r terminal-tetris-win-x64.zip ./Terminal.Tetris/bin/Release/netcoreapp3.1/win-x64
    - name: Build linux-x64
      run: dotnet publish -r linux-x64 -c Release --self-contained --no-restore && zip -r terminal-tetris-linux-x64.zip ./Terminal.Tetris/bin/Release/netcoreapp3.1/linux-x64
    - name: Build osx-x64
      run: dotnet publish -r osx-x64 -c Release --self-contained --no-restore && zip -r terminal-tetris-osx-x64.zip ./Terminal.Tetris/bin/Release/netcoreapp3.1/osx-x64
    - name: Detect Artifact name
      run: echo ::set-env name=RELEASE_ARTIFACT_NAME::$(date)
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
    - name: Upload Release Asset win-x64 
      id: upload-release-asset-win-x64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
        asset_path: terminal-tetris-win-x64.zip
        asset_name: ${{env.RELEASE_ARTIFACT_NAME}}
        asset_content_type: application/zip
    - name: Upload Release Asset linux-x64 
      id: upload-release-asset-linux-x64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
        asset_path: terminal-tetris-linux-x64.zip
        asset_name: ${{env.RELEASE_ARTIFACT_NAME}}
        asset_content_type: application/zip
    - name: Upload Release Asset osx-x64 
      id: upload-release-asset-osx-64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
        asset_path: terminal-tetris-osx-x64.zip
        asset_name: ${{env.RELEASE_ARTIFACT_NAME}}
        asset_content_type: application/zip
