name: Release

on:
  push:
    branches: [ master ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Generate build number
      id: buildnumber
      uses: einaregilsson/build-number@v2 
      with:
        token: ${{secrets.GITHUBTOKEN}}  
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore 
    - name: Build win-x64
      run: dotnet publish -r win-x64 -c Release --self-contained --no-restore && 
           zip -r -j terminal-tetris-win-x64.zip ./Terminal.Tetris/bin/Release/netcoreapp3.1/win-x64/publish/*
    - name: Build linux-x64
      run: dotnet publish -r linux-x64 -c Release --self-contained --no-restore && 
           zip -r -j terminal-tetris-linux-x64.zip ./Terminal.Tetris/bin/Release/netcoreapp3.1/linux-x64/publish/*
    - name: Build osx-x64
      run: dotnet publish -r osx-x64 -c Release --self-contained --no-restore && 
           zip -r -j terminal-tetris-osx-x64.zip ./Terminal.Tetris/bin/Release/netcoreapp3.1/osx-x64/publish/*
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
      with:
        tag_name: v1.0.${{ steps.buildnumber.outputs.build_number }}
        release_name: Release v1.0.${{ github.ref }}
        draft: false
        prerelease: false
    - name: Upload Release Asset win-x64 
      id: upload-release-asset-win-x64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} 
        asset_path: terminal-tetris-win-x64.zip
        asset_name: terminal-tetris-win-x64.zip
        asset_content_type: application/zip
    - name: Upload Release Asset linux-x64 
      id: upload-release-asset-linux-x64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: terminal-tetris-linux-x64.zip
        asset_name: terminal-tetris-linux-x64.zip
        asset_content_type: application/zip
    - name: Upload Release Asset osx-x64 
      id: upload-release-asset-osx-64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} 
        asset_path: terminal-tetris-osx-x64.zip
        asset_name: terminal-tetris-osx-x64.zip
        asset_content_type: application/zip
